# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10EErEMRSIv4uiLeLHB6XDNO_MdLls0OK
"""

import streamlit as st
import os
! pip install fastbook
import fastbook
fastbook.setup_book()
from fastbook import *
from PIL import Image
import pandas as pd
# รายการคลาส
all_classes = ["ADHD","Normal"]

sample_imagesaxial = {
        "Normal Axial sample" : "Sample/Normal Axial sample.png",
        "ADHD Axial sample": "Sample/ADHD Axial sample.PNG",}
sample_imagessagittal = {
         "Normal Sagittal sample" : "Sample/Normal Sagittal sample.png",
        "ADHD Sagittal sample": "Sample/ADHD sagittal sample.PNG",}
sample_imagescoronal = {
        "ADHD Coronal sample": "Sample/ADHD Coronal sample.PNG",
        "Normal coronal sample" : "Sample/Normal coronal sample.png", }

# ฟังก์ชันสำหรับโหลดโมเดล
import torch
import torch.nn as nn
import torchvision.models as models
import streamlit as st

# Assuming `all_classes` is defined somewhere globally

def load_model(model_path):
    """Helper function to load a model from a given path"""
    try:
        # Initialize a pre-trained ResNet50 model
        model = models.resnet50(pretrained=True)

        # Modify the final fully connected layer to match the number of classes in your dataset
        num_features = model.fc.in_features
        model.fc = nn.Linear(num_features, len(all_classes))  # Change output layer

        # Load the model weights from the given path
        model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu')))

        # Set the model to evaluation mode
        model.eval()
        return model
    except Exception as e:
        print(f"Error loading model from {model_path}: {e}")
        raise

@st.cache_resource
def load_modelaxial():
    return load_model('./Axial_model_.pkl')

@st.cache_resource
def load_modelcoronal():
    return load_model('./Coronal_model_.pkl')

@st.cache_resource
def load_modelsagittal():
    return load_model('./Sagittal_model_.pkl')


# ฟังก์ชันสำหรับแปลงภาพ
def preprocess_image(image):
    if image.mode != 'RGB':
        image = image.convert('RGB')
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    return transform(image).unsqueeze(0)

# ฟังก์ชันสำหรับทำนายผลลัพธ์
def predict_image(image, model):
    with torch.no_grad():
        output = model(image)
        threshold = 0.1
        predicted_labels = (output > threshold).squeeze().int()
        return predicted_labels

# ฟังก์ชันหลัก
def main():
    modelaxial = load_modelaxial()
    modelcoronal = load_modelcoronal()
    modelsagittal = load_modelsagittal()
    image = None

    st.title("ADHD Detector")
    st.write("Upload an image")

    uploaded_fileaxial = st.file_uploader("Choose an axial image...")
    uploaded_filecoronal = st.file_uploader("Choose an coronal image...")
    uploaded_filesagittal = st.file_uploader("Choose an sagittal image...")

    with st.expander("Or choose from sample axial here..."):
        axialsample = st.selectbox(label="Select here", options=list(sample_imagesaxial.keys()), label_visibility="hidden")
        col1, col2, col3 = st.columns(3)
    with st.expander("Or choose from sample coronal here..."):
        coronalsample = st.selectbox(label="Select here", options=list(sample_imagescoronal.keys()), label_visibility="hidden")
        col1, col2, col3 = st.columns(3)
    with st.expander("Or choose from sample sagittal here..."):
        sagittalsample = st.selectbox(label="Select here", options=list(sample_imagessagittal.keys()), label_visibility="hidden")
        col1, col2, col3 = st.columns(3)

    if uploaded_file is not None:
        imageaxial = Image.open(uploadedaxial_file)
        imagecoronal = Image.open(uploadedcoronal_file)
        imagesagittal = Image.open(uploadedsagittal_file)
        st.imageaxial(imageaxial, caption='Uploaded axial Images', use_column_width=True)
        st.imagecoronal(imagecoronal, caption='Uploaded coronal Images', use_column_width=True)
        st.imagesagittal(imagesagittal, caption='Uploaded sagittal Images', use_column_width=True)
        st.write("")
    elif sample != "None":
            imageaxial = Image.open(sample_imagesaxial[axialsample])
            imagecoronal = Image.open(sample_imagescoronal[coronalsample])
            imagesagittal = Image.open(sample_imagessagittal[sagittalsample])
            st.image(image, caption=f'Selected Sample: {sample}', use_column_width=True)
            st.write("")
    else:
        imageaxial = None
        imagecoronal = None
        imagesagittal = None
        ADHD =0
        Normal = 0

    if image is not None:
        image_tensoraxial = preprocess_image(imageaxial)
        image_tensorcoronal = preprocess_image(imagecoronal)
        image_tensorsagittal = preprocess_image(imagesagittal)

        predicted_labelsaxial = predict_image(image_tensor, modelaxial)
        predicted_labelscoronal = predict_image(image_tensor, modelcoronal)
        predicted_labelssagittal = predict_image(image_tensor, modelsagittal)

        st.subheader("Predicted labels:")
        if predicted_labelsaxial.sum() == 0:
            st.write("Can't find file")
        else:
            for idx, label in enumerate(all_classes):
                if predicted_labelsaxial[idx] == 1:
                  if label == 'ADHD':
                    ADHD += 1
                  else:
                    Normal += 1

        if predicted_labelscoronal.sum() == 0:
            st.write("Can't find file")
        else:
            for idx, label in enumerate(all_classes):
                if predicted_labelscoronal[idx] == 1:
                  if label == 'ADHD':
                    ADHD += 1
                  else:
                    Normal += 1
        if predicted_labelssagittal.sum() == 0:
            st.write("Can't find file")
        else:
            for idx, label in enumerate(all_classes):
                if predicted_labelssagittal[idx] == 1:
                  if label == 'ADHD':
                    ADHD += 1
                  else:
                    Normal += 1

    if ADHD > Normal:
        st.write("ADHD")
    else:
        st.write("Normal")

    st.subheader("Credits")
    st.write("By : Natthakanya Bhummichitra | AI-BuildersXDarunsikkhalai")
    st.markdown("Source : [Github]('https://github.com/NatthakanyaB/ADHD-Detector')")


if __name__ == "__main__":
    main()
